export enum ColorCodes {
    Black = "§0",
    DarkBlue = "§1",
    DarkGreen = "§2",
    DarkCyan = "§3",
    DarkRed = "§4",
    DarkPurple = "§5",
    Gold = "§6",
    Gray = "§7",
    DarkGray = "§8",
    Blue = "§9",
    Green = "§a",
    Cyan = "§b",
    Red = "§c",
    LightPurple = "§d",
    Yellow = "§e",
    White = "§f",
    Bold = "§l",
    Strikethrough = "§m",
    Underline = "§n",
    Italic = "§o",
    Reset = "§r",
}
